dataset: SMCAD_BIG
num_workers: 8
model:
  gMHA_type: Hadamard
  gnn_type: GINEConv
  nlayer_gnn: 2
  nlayer_mlpmixer: 3
  hidden_size: 512
train:
  runs: 1
  epochs: 10
  batch_size: 16
  lr: 0.000001
  lr_patience: 10 # Anzahl Schritte, bevor Lernrate reduziert wird
  lr_decay: 0.5 # Faktor, um den Lernrate reduziert wird
  wd: 0.0 # L2-Regularisierung, zur Vermeidung von Overfitting
  dropout: 0.0 # Droput-Rate für die Regulierung während des Trainings
  mlpmixer_dropout: 0.0 # Dropout-Rate für MLPMixer
  min_lr: 0.0000001
  multiscale: True # Aktiviert multiscale-training
metis:
  enable: True # Aktiviert Metis-Partitionierung
  online: False # Aktivert Online-Datenaugmentation durch Partitionierung
  n_patches: 128
  drop_rate: 0.1
  num_hops: 1
pos_enc:
  rw_dim: 40 # These make it such that we don't use node pes
  patch_rw_dim: 40 # Make equal to above for new version
  lap_dim: 0
  patch_num_diff: 0
jepa:
  num_context: 1
  num_targets: 4
device: 0